#!/bin/sh

#Usage: gulp && ./to_ghpages

git commit -am "Save uncommited changes (WIP)"
git branch --delete --force gh-pages
git checkout --orphan gh-pages
git add -f dist
git commit -m "Rebuild GitHub pages"
git filter-branch -f --prune-empty --subdirectory-filter dist && git push -f origin gh-pages && git checkout -

# git add dist && git commit -m "Publishing UniquePasswordBuilder to GitHub pages"
# git push origin :gh-pages
# git subtree push --prefix dist origin gh-pages
# git reset --soft HEAD~
